### ISSUE TITLE
Improve boilerplate upgrade process

### ISSUE THREAD

**Issue by driskull** [Esri/application-boilerplate-js#106]
Upgrading the boilerplate should be easy. We need to make it more like a supported application and not a sample with a boilerplate class.

**Comment by alaframboise** [comment]
Agreed. You should be able to just pull the latest into a project without it stepping on user config settings/customizations.

**Comment by driskull** [comment]
The part I struggle with is that users of the boilerplate have trouble when it affects their `application.js` file. However, that file can be anything so I'm not sure how we can allow upgrades to that file. Its basically an example. 

So maybe we just need to separate out examples and leave the `application` files blank and alone.

**Comment by driskull** [comment]
@alaframboise would you be able to look at the branch `4masterts` and let me know your thoughts?

**Comment by alaframboise** [comment]
Will do!

**Comment by driskull** [comment]
https://github.com/Esri/application-base-js
