### ISSUE TITLE
Update gh-pages to 4master

### ISSUE THREAD

**Issue by gavinr** [Esri/application-boilerplate-js#109]
Right now, the version of this app on `gh-pages` (http://esri.github.io/application-boilerplate-js/index.html) is showing white lines in the basemap, i think because it's using an old version of the 4.x jsapi. 

![image](https://cloud.githubusercontent.com/assets/209355/24677682/39d71012-194d-11e7-8024-607f27fb1515.png)

If we updated to the latest `4master` branch, which includes [a fix](https://github.com/Esri/application-boilerplate-js/commit/dc6900ecf82e63c620ad2c821576a5c9e869915a) from @driskull , it appears to fix that problem.

**Comment by driskull** [comment]
thanks @gavinr . should be fixed now :)

**Comment by gavinr** [comment]
Looking good. Thanks!
