### ISSUE TITLE
Error handling (4masterts)

### ISSUE THREAD

**Issue by nicksenger** [Esri/application-boilerplate-js#111]
The typescript boilerplate is currently failing silently for me somewhere in boilerplate.init()

I'm going to refactor this a bit and add some error handling to the asynchronous code so that I can use it in the embedded group gallery. Will make a PR to this repo when finished.

**Comment by driskull** [comment]
Yeah, it's in progress. Complete rewrite going on at this time.

Once that's done. I still need to figure out how to make this more "updatable", support handling more than one group/webmap/webscene and redesign error UI using calcite.

**Comment by nicksenger** [comment]
@driskull 

Okay, great. I just spoke with Kelly and for now I am going to get the group embedded gallery working by making some changes to the existing boilerplate where necessary, then port it over to your rewrite when that is ready.

I'll push up any changes that I make to a separate branch or something in case it helps with the rewrite at all.

**Comment by driskull** [comment]
👍 thanks
