### ISSUE TITLE
4masterts Feedback

### ISSUE THREAD

**Issue by driskull** [Esri/application-boilerplate-js#114]
- [x] Use CacliteMaps or nothing. Calcite-web is only for web pages
- [x] Would prefer not to use any calcite since it should be framework independent
- [x] Separate boilerplate code into its own repo. Have other repos use TypeScript, vanilla JS, frameworks, grunt, etc. Don't force users to use TS.

**Comment by driskull** [comment]
@kellyhutchins @alaframboise @nicksenger

 I think for 4x, this repo will only be the Boilerplate Class, which will be written in TS.

We will create other repos that import this class and use it with and without Typescript and we can create even more repos that use it with things like calcite maps or other frameworks.

This way, I can write and maintain the boilerplate class separately in TypeScript but it can be consumed using TS or whatever.

I've created the branch for it here:
https://github.com/Esri/application-boilerplate-js/tree/4masterts-class-only

Thoughts?

I think we can have at least one other repo which will have all the other common app stuff like displaying errors, loading spinners, dojo config setup, etc. This could be written using TS or without. I'm up for either. Or we have two repos, one for each.

We could have more repos with examples only, that users can use. This way, we keep the examples and boilerplate separated so that people dont use the examples expecting that they won't change.

-Matt

**Comment by alaframboise** [comment]
@driskull I think this is a great idea. I think it's the only way to truly separate the `base` from the `apps`. I think we should start from ground zero for the 4.x stuff. It would be great if we had something like this:

```
app-template-base
app-template-map
app-template-calcite-maps
app-template-group
```

**Comment by driskull** [comment]
I was thinking it would be more like this:

- `configurable-app-js` This is the base application class. (owned by @driskull )
- `configurable-app-boilerplate-js` This is the simple application with basic file structure. (owned by @kellyhutchins )
- `configurable-app-example-group` ... (owned by ???)
- `configurable-app-example-calcite-maps` ... (owned by @alaframboise )
- ... any other examples?

**Comment by kellyhutchins** [comment]
I think it all sounds good but I think we should also have a Calcite Web example too. Its useful and people are already working with it.

**Comment by kellyhutchins** [comment]
@driskull  I hate naming things its so hard. :)

I think ApplicationHelper works.

**Comment by driskull** [comment]
@kellyhutchins it is, soo hard.

**Comment by alaframboise** [comment]
Isn't it all portal stuff? What about `ApplicationBase` or `ApplicationConfig` or `ArcGISConfig`?

**Comment by kellyhutchins** [comment]
ApplicationBase sounds ok to me. I think ApplicationConfig would be confusing because of the other config files we have.

**Comment by alaframboise** [comment]
`ConfigurableAppBase` or `AppPortalBase`

**Comment by driskull** [comment]
ApplicationBase works. I'll go with that.

Ill create the following repo on ArcGIS Github which we can transfer to Esri once ready.

- `application-base-js`

I think we should keep this one for the boilerplate since people already know about this and we have 4x on here already. The name of the repo still works.

- `application-boilerplate-js`

Once I get the repo set up here on the 4masterts branch, you guys can create repos on ArcGIS for

- `configurable-app-example-webscene`
- `configurable-app-example-group`
- `configurable-app-example-calcite-maps`

**Comment by MikeTschudi** [comment]
@driskull, perhaps combine the examples as folders in a single repo? One-stop shopping for examples and uses less of the ArcGIS account quota.

**Comment by driskull** [comment]
sure. I'll create and manage the base repo. I'll setup the boilerplate repo and @kellyhutchins will manage it.

The other example repos I'll leave up to @alaframboise and whoever else to manage/maintain.

**Comment by alaframboise** [comment]
@kellyhutchins I'm all for a single `configurable-app-examples` repo as @MikeTschudi suggests. We just need to figure out the structure so each can have it's own configs and if there will be shared code. e.g.

```
\applicationbase\
\map\
\scene\
\group\
\shared\
```

**Comment by driskull** [comment]
Its probably best not to share the code so people can just copy the folder of the example they like and tweak it.

**Comment by alaframboise** [comment]
ya, i was just thinking that some helper modules would be totally shareable e.g. `viewManager`

**Comment by kellyhutchins** [comment]
I like @MikeTschudi  idea of combining it all in one repo. That way users can quickly find the examples and pick the one they want. I also think we should keep the code separate in the folders so its easy to copy only the code you want without having to also pull shared code from various places.

**Comment by MikeTschudi** [comment]
We'll already have code sharing--the boilerplate--so a `shared` folder wouldn't be an outlier.

Perhaps have subfolder placeholders in each example:  Each subfolder would have a text file with a name like `insert_boilerplate_here.md` (or another `README.md`?); inside the file would be the link to the repo or folder containing what should be inserted, e.g., the boilerplate's `dist` folder for one, the `share` folder for another.

Updating one's app to use an updated boilerplate would be as simple as replacing everything in the boilerplate subfolder. Boilerplate and shared code are maintained in one location and used in multiple.

Should the `shared` folder be part of the boilerplate? From this viewpoint, the boilerplate provides common elements useful for creating apps, and one picks what one needs from it.  E.g., it'll supply routines for displaying webmaps, webscenes, and groups, but a typical app won't use all three, so the boilerplate is already acting like a common library.

**Comment by MikeTschudi** [comment]
@kellyhutchins, are you suggesting keeping the boilerplate with the examples and the shared code in one repo? If the individual parts can be updated separately--especially the boilerplate and/or shared--this would simplify the documentation and use. 

But keeping the boilerplate in a separate repo seemed valuable because it emphasized that it can evolve separately from one's app, like the JSAPI evolves separately. The crisper the separation between boilerplate and app, the easier it is to maintain.  It also might make it easier to source the boilerplate in TypeScript while distributing it in JavaScript for use in TypeScript or JavaScript apps.

**Comment by kellyhutchins** [comment]
No I was suggesting all the examples in one repo and the boilerplate in another.

**Comment by driskull** [comment]
I have the two repos setup here:

https://github.com/ArcGIS/application-base-js
https://github.com/ArcGIS/application-boilerplate-js

Once we get these approved and the Readme's updated, we can move them to the Esri account on github.

This repo we can rename to "application-boilerplate-3x-js" and mark it as deprecated.

I will work on the `application-base-js` readme. Can one of you tackle the `application-boilerplate-js` readme and repo? It should have everything it needs including NPM, Grunt.

Also, we need the examples repo created.

**Comment by alaframboise** [comment]
@driskull why not just `app-template-base` and `app-template-examples`? The '.js' suffix is only handy when there are examples in many different languages.

**Comment by driskull** [comment]
Incase there are ever different languages. We've always done that for templates and other things.

**Comment by alaframboise** [comment]
@driskull your call, but IMHO `application` just seems too generic... ;)
