### ISSUE TITLE
Do we still need commonConfig file?

### ISSUE THREAD

**Issue by driskull** [Esri/application-boilerplate-js#39]
@kellyhutchins Do we still need commonConfig file? Would there be a better way to do this via some rest service?

**Comment by kellyhutchins** [comment]
@driskull  we added it to support the current portal implementation. However we added it mostly to handle support for common services and the bing key. Some of that might not be such an issue anymore and may be discoverable in other ways. I'm going to sit down with Ian in mid-January and look at the portal template workflow and see if we can get rid of it.  I'll keep you posted.

**Comment by driskull** [comment]
cool thanks. Maybe you can talk to him about #33 as there might be a better way to do it as well.

**Comment by kellyhutchins** [comment]
That one is trickier. I spoke to Blake about it a bit and we couldn't come up with an alternative but  I have a note to spend a bit more time investigating alternatives.

**Comment by driskull** [comment]
We already do a call to get the organization info, maybe it could be within that request?
