### ISSUE TITLE
GroupID Configured from App values is not honoured in boilerplate

### ISSUE THREAD

**Issue by sumitzarkar** [Esri/application-boilerplate-js#41]
HI @driskull ,

GroupID Configured from App values is not honoured in boilerplate.
This can be fixed by adding following code in the method _queryApplicationConfiguration in template.js at line #382
```javascript
//Get the groupID from the app values
if (response.itemData.values.group !== "") {
 this.config.group = response.itemData.values.group;
}
```

**Comment by driskull** [comment]
hey @sumitzarkar 

It looks like it should get mixed into the appConfig property at [line 385](https://github.com/Esri/application-boilerplate-js/blob/master/application_boilerplate/js/template.js#L385)
which should then be mixed in at [line 113](https://github.com/Esri/application-boilerplate-js/blob/master/application_boilerplate/js/template.js#L103) before it queries for the group and items.

Is it not getting into the config property? or is the group an empty string in the app values?

cc @kellyhutchins

**Comment by sumitzarkar** [comment]
Hi @driskull 

Thank you Matt for your reply.

Yes you are correct the groupid is getting mixed in properly.
It was my mistake in the application where I was not initialising the boiler plate in proper sequence and the value for groupid configured in the defalut.js was carried forward without being overridden by the appconfiguration.

**Comment by driskull** [comment]
Thanks @sumitzarkar. We have a pending update that will mix in things a little better.
