### ISSUE TITLE
Add support for boolean url parameters to template.js

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-boilerplate-js#44]
Many of the url params I use in templates are boolean but when retrieved as url params they are strings. I think we should add some logic into the _getUrlParamValues function to handle the conversion. Something like this? 

  var item = urlObject.query[items[i]];
                        obj[items[i]] = item === "true" || (item == "false" ? false : item);     

@driskull  thoughts?

**Comment by driskull** [comment]
@kellyhutchins Makes sense to me. I had done this for the public gallery app.

**Comment by kellyhutchins** [comment]
Cool I'll add it in.

**Comment by driskull** [comment]
hey @kellyhutchins did this get put in yet?

**Comment by kellyhutchins** [comment]
@driskull  not yet.
