### ISSUE TITLE
Changing group from configuration panel has no effect 

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/application-boilerplate-js#47]
@driskull 
Steps to reproduce:
1. Share group **"A"** using a gallery template app
2. Open configuration panel, it correctly displays group **"A"** that was used to publish the app
3. Now change the group to **"B"** using configuration panel
4. Notice that the app reloads and shows group **"B"**
5. Click Save and Done and launch the app again from the app item
6. Notice that the app launches and displays group **"A"** instead of group **"B"**
7. Changing the group has no effect

We see that when a gallery app is published, the app url contains the groupid of the group that was used to publish the app. When a different group is chosen using the configuration panel, it is saved to app configuration. However, the app url still retains the original groupid that was used to publish the app. Hence, when the app launches, boilerplate gives highest priority to URL parameters and ignores the groupid that was saved to app configuration.

We don't think this is a boilerplate issue, since we are of the opinion that url parameters must always be given highest priority. What would be ideal is that the configuration app (configureApp.html) should update the app url with the new groupid when the group is changed.

Please suggest a solution or a workaround that will reflect the changed group.

**Comment by driskull** [comment]
cc @kellyhutchins.

Kelly, is there a reason the item URL has the group stored in it? It seems like the app should be able to handle which group to use and it shouldn't be forced in the URL because then the app cannot change it. Thoughts?

Ideally, it would not be there at all. Only set in the application JSON.

**Comment by driskull** [comment]
cc @iwittenmyer.

**Comment by kellyhutchins** [comment]
@driskull  tested with the templates in online and they do read the group id from the app data so it seems like we don't need the url param. Sounds like a bug should be submitted to online to remove the group id from the url param for the configured app.

**Comment by driskull** [comment]
Submitted issue for this. 3131

**Comment by kellyhutchins** [comment]
Issue resolved for 3.13 closing here.
