### ISSUE TITLE
Allow ordering of the mixin from templateConfig.js

### ISSUE THREAD

**Issue by driskull** [Esri/application-boilerplate-js#49]
Some users may want to mixing resources differently. Should we allow this by a configuration option in templateConfig.js?

**Comment by driskull** [comment]
If anyone else wants to take a stab at this let me know :+1:

**Comment by kellyhutchins** [comment]
@driskull  can you think of a reason why someone developing a template would want to modify the order of mixing in the resources?

**Comment by driskull** [comment]
not really. There may be one though.

**Comment by kellyhutchins** [comment]
@driskull  my 2 cents would be to leave this out until we come up with a compelling template use case. I'd hate to make the boilerplate more complicated for a scenario that may or may not come up.

**Comment by driskull** [comment]
ok sounds good.
