### ISSUE TITLE
Standardize support for url params

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-boilerplate-js#57]
Add a new class that handles supporting map params like center, zoom, level, extent.

**Comment by driskull** [comment]
Add:
- center
- level
- zoom
- extent

Maybe:
- marker=-79.234826;38.147884;;Race start and finish;Grindstone 100 Ultra Marathon
- find=380 new york st,redlands,ca
- basemapUrl
- basemapReferenceUrl
- url
- urls
- layers=show:1,2

@kellyhutchins any comments on which of these to support? What is the difference between zoom and level?

**Comment by kellyhutchins** [comment]
@driskull  zoom and level are the same we should probably use level as teh url param since that's what online uses. 

I think the most commonly requested params are center, extent, level and find so those are the ones I think we should support. I don't think we should add support for the others to the template boilerplate at this time.

**Comment by driskull** [comment]
@ycabon for 4.0 do you think it would make sense to just rename the map option from "zoom" to "level" if that's what we're calling it everywhere?

**Comment by kellyhutchins** [comment]
Pull request looks good - merged.

**Comment by ycabon** [comment]
@driskull for 4.0, we are using zoom, not level. WebMap has also some props like min/maxZoom. Level only exists in LOD.

**Comment by driskull** [comment]
hmmm. consistency is tough :(

The online viewer uses "level" as a URL parameter so thats what our apps were going to use. I'm wondering if we should use "zoom" instead.

Maybe we should just add both so someone could use either of them lol.

**Comment by kellyhutchins** [comment]
@driskull  i have some apps that use zoom as a url param to hide/show the zoom slider... so maybe just stick with level and make sure we doc what setting the value means?

**Comment by driskull** [comment]
ok. Seems like the 4.0 API should use level, zoomLevel or just maxLevel, MinLevel. zoom is kinda vague. zoom what?

**Comment by ycabon** [comment]
Another to see that feature could be to encode the map location as one parameter? center/zoom
