### ISSUE TITLE
Return createMap deferred from startup. 

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-boilerplate-js#60]
Return the createMap deferred from main.startup()
It is useful to have a the startup() function return a Deferred
so that calling code can wait for the webmap to load before
adding application-specific functionality to the map.

Issue originated in map tools repo: 
https://github.com/Esri/map-tools-template/pull/9/commits

**Comment by driskull** [comment]
6623ad88f4c337dd7e3d10ef244e200f2fa8b128

**Comment by driskull** [comment]
hey @kellyhutchins this should do it. We can just merge it in when 3.14 releases.

**Comment by kellyhutchins** [comment]
merged.
