### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by asizer** [Esri/application-boilerplate-js#62]
The "About web application templates" link in the [Getting Started section](https://github.com/Esri/application-boilerplate-js/blob/master/README.md#getting-started) points [to a broken link](http://resources.arcgis.com/en/help/arcgisonline/#/*%20%20%20About_web_application_templates/010q000000nt000000/).

**Comment by driskull** [comment]
thanks @asizer. Should be fixed now.
