### ISSUE TITLE
4.x: Use JSON instead of dojo object

### ISSUE THREAD

**Issue by alaframboise** [Esri/application-boilerplate-js#70]
Is there any chance we can use JSON instead of a dojo to describe the app configuration for the 4.x version of the boilerplate? It looks like the webmap version is already taking that approach anyhow.

https://github.com/Esri/application-boilerplate-js/blob/master/application_boilerplate/config/demoMap.js
vs
https://github.com/Esri/application-boilerplate-js/blob/4.0master/webscene_application_boilerplate/config/demoScene.json

@kellyhutchins @driskull

**Comment by driskull** [comment]
Its better that we have it as a module that we can load as a dependency rather than just JSON through esriRequest IMO.

**Comment by driskull** [comment]
done.
