### ISSUE TITLE
4x boilerplate sanity check

### ISSUE THREAD

**Issue by driskull** [Esri/application-boilerplate-js#76]
Could you go over the 4x boilerplate in the "4master" branch and provide feedback on:

- Layout, structure, and organization
- Naming of things
- Code quality
- Readme.md documentation

If anything doesn't make sense, needs additional documentation or is missing anything... ***Just add it!***

https://github.com/Esri/application-boilerplate-js/tree/4master

**Comment by kellyhutchins** [comment]
@SpatialAgent  we may want to update test your 4.0 apps

**Comment by alaframboise** [comment]
@kellyhutchins is it too early to add the theme spec to the JSON definition?

https://github.com/Esri/application-boilerplate-js/blob/master/application_boilerplate/config/defaults.js#L32

**Comment by kellyhutchins** [comment]
@alaframboise  I think its too early. We have to think about what we can realistically support in the template apps. But its something we are thinking about so once we have a better idea of what is possible we can talk about adding it.

**Comment by driskull** [comment]
Agreed, but let me know if there are any common properties that all templates should have and we are currently missing.

**Comment by driskull** [comment]
closing
