### ISSUE TITLE
4x boilerplate: Support shared theming 

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-boilerplate-js#78]
Add support for shared theming to the 4x boilerplate. 
https://github.com/SpatialAgent/local-perspective/pull/28/files

Sample theme: https://opendatadev.arcgis.com/api/v2/sites/594

**Comment by kellyhutchins** [comment]
fyi @MarkhamShofner

**Comment by MarkhamShofner** [comment]
And if we want to go down the css-injection route (as opposed to the currently discussed direct JavaScript manipulation) here is a repo I mocked up last month that retrieves and injects css from an external endpoint. https://github.com/MarkhamShofner/shared-styles-demo

**Comment by driskull** [comment]
Assigning to @kellyhutchins as well. Let me know when there's a task for me to do :)

**Comment by driskull** [comment]
closing. old
