### ISSUE TITLE
4x boilerplate: Add support for reading app values from local storage

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-boilerplate-js#90]
I'd like to add support for reading app values from local storage so we can take advantage of this capability in the app config panel. If the app was able to read app values from local storage we'd be able to support live preview and undo/redo capability in the default template config panel. 
The app could use the values from app storage to provide live preview and then once the save button was hit on the config panel we'd write out the appid and clear local storage. 

@driskull  thoughts?

**Comment by driskull** [comment]
Yep! sounds like a great idea. I remember we talked about this before.

**Comment by driskull** [comment]
@kellyhutchins would this require that the app have an appid? Otherwise, we don't want to have settings conflict with different apps for a user. Need some kind of unique identifier.

**Comment by kellyhutchins** [comment]
@driskull   yep - but once you enter config mode we have an appid so we'd use that appid. If the template was locally hosted and didn't have an appid then we wouldn't write anything to storage.

**Comment by driskull** [comment]
do you need functions to set or remove the local storage item from the boilerplate or would that be done outside?

**Comment by kellyhutchins** [comment]
We'd do that from the config panel so I don't think we'd need functions in the app.

**Comment by driskull** [comment]
Reassigned for verification

**Comment by driskull** [comment]
Is this good @kellyhutchins ?

**Comment by driskull** [comment]
closing. reopen if necessary.
