### ISSUE TITLE
4.1: IdentityManager console error

### ISSUE THREAD

**Issue by alaframboise** [Esri/application-boilerplate-js#96]
Good news: The IdentityManager is styled and no other .css refs are required. Yeah!
Bad news: IdentityManager is throwing a console error in the boilerplate.js.

Just swap the 4.0 refs to 4.1 and you should see:

```
init.js:153 Error: User is not signed in.(…) "Error: User is not signed in.
    at Error (native)
...
```

**Comment by dasa** [comment]
I'm not able to reproduce this issue.

**Comment by alaframboise** [comment]
@dasa I just tested again and it looks like this was fixed in a recent build. We can close this one. Thanks.
