### ISSUE TITLE
Invalid Repo URL

### ISSUE THREAD

**Issue by dasa** [Esri/application-boilerplate-js#97]
The repo's Website URL is 404 at: http://esri.github.io/application-boilerplate-js/application_boilerplate/

**Comment by alaframboise** [comment]
@dasa you mean in the short description at the top of the repo right? If so I just changed it.

I think we are overdue for a master > gh-pages merge too! @driskull

**Comment by driskull** [comment]
done 👍

**Comment by dasa** [comment]
Thanks!
