### ISSUE TITLE
Boilerplate Create > App > Using a Template fails to load webscene

### ISSUE THREAD

**Issue by alaframboise** [Esri/application-boilerplate-js#98]
In My Content, if you check on a webscene and create a boilderplate template app through the menu, the Configuration window fails to load the item (the webscene you originally checked). To view it, you have to use the Configuration window to manually reselect the webscene. I looked at the boilerplate.results and the webscene is definitely missing. I think this is because the mixin code isn't getting the checked webscene from the newly created app or the webscene wasn't sent to the template from AGO. Not sure if this is an AGO bug or ours. Thoughts?

The other app templates don't seem to have this issue - probably because they have default webmap/webscene in the config.

Steps to repro:
1. Configure the Boilerplate with default config JSON.
2. In My Contents check on a webscene.
3. Create a New Web App by selecting the Boilerplate.
4. In the Configuration window > View (Error).
5. Now manually re-select your webscene > View.

![image](https://cloud.githubusercontent.com/assets/2539681/18837477/bd95f074-83b8-11e6-85c1-c127990bccb9.png)

![image](https://cloud.githubusercontent.com/assets/2539681/18837644/598426e0-83b9-11e6-884e-e063a741eeee.png)

![image](https://cloud.githubusercontent.com/assets/2539681/18837802/0034d386-83ba-11e6-90e2-d0b0b8c96269.png)

![image](https://cloud.githubusercontent.com/assets/2539681/18840026/152ded42-83c2-11e6-8ff0-05b87201a616.png)

**Comment by driskull** [comment]
@alaframboise this seems like an issue with the webscene viewer. Can you create an issue for them?

**Comment by alaframboise** [comment]
Hey @driskull, I'm guess I'm not sure what this has to do with the webscene viewer. I can reproduce the same error with a webmap. I think the issue is that the webmap and webscene url param is not being sent to the template.

![image](https://cloud.githubusercontent.com/assets/2539681/18841223/e1cf4974-83c5-11e6-83ee-74f3b67d841a.png)

**Comment by driskull** [comment]
Its a portal issue though, right? The boilerplate works with url params.

**Comment by alaframboise** [comment]
Ya, I think so. I just wasn't sure if the Boilerplate mixin was failing to extract it or if it's not there. From what I can see in the debugger, the Boilerplate isn't being sent the webmap/websene ID when you create a template this way. If you think portal and Boilerplate is good, I'll log it.

**Comment by driskull** [comment]
Look at the network inspector and see if its in the item. If its not, then its a portal issue.

**Comment by alaframboise** [comment]
I'm only seeing one request to Boilerplate with the appid. However if you set the webmap/webscene property, I see two requests. That's why I thought it was a Boilerplate error. Should the Boilerplate make a request for the map/scene if only sent an appid?

![image](https://cloud.githubusercontent.com/assets/2539681/18842986/d1d324c2-83cb-11e6-8f0c-52d423d20f40.png)

![image](https://cloud.githubusercontent.com/assets/2539681/18843105/49072516-83cc-11e6-8c68-3d15dc76854f.png)

**Comment by driskull** [comment]
@alaframboise you have to look at the item data not just the item. The item data should have either a webmap or webscene in it.

**Comment by driskull** [comment]
The boilerplate will get the webmap or webscene from the URL, application item or config. If it doesn't exist in any of those then it cant get it. 

This needs a little more research to see where the failure lies then an issue can be opened in the appropriate place.

**Comment by alaframboise** [comment]
Here's data?f=json for the initial request and for the second request after manually selecting a webscene. It think this is what you were after? Why is that data missing the first time around? Portal didn't send it?

![image](https://cloud.githubusercontent.com/assets/2539681/18843886/b1a8e4e4-83cf-11e6-9d6c-b933798bab11.png)

![image](https://cloud.githubusercontent.com/assets/2539681/18843894/bbf70368-83cf-11e6-9836-ad45420436b5.png)

**Comment by driskull** [comment]
I'm guessing portal doesn't save the webscene when the item is originally created.

**Comment by alaframboise** [comment]
Yip, that what I was thinking too. I'll log a portal issue. In the meantime, i'll hardcode a webmap/webscene into the config to avoid the failure.

**Comment by iwittenmyer** [comment]
that workflow of selecting a map or scene from the content grid and creating an app with it isn't supported, but maybe we can look into adding that capability as an enh.

**Comment by driskull** [comment]
Seems like it would be a good enhancement. Otherwise, users are dropped into an empty app.

**Comment by alaframboise** [comment]
@iwittenmyer Create > App is the only way I know how to test a 4.0 template unless there's a magic way to add 3d templates into the new Create App dialog.

**Comment by driskull** [comment]
Lets move this discussion into a Portal issue since this isn't a boilerplate issue. :)

**Comment by iwittenmyer** [comment]
i'll log the enh, because this scenario has not yet been supported. the workflow was pick the app, then pick the scene/map/group
